### ISSUE TITLE
404 - Page Not Found -     ESP32_Display_Panel/examples  /README.md/

### ISSUE THREAD

**Issue by mrmonteith** [esp-arduino-libs/ESP32_Display_Panel#109]
On the Panel Test Readme.MD, the section on 
`If using a custom board, follow the [steps](https://github.com/esp-arduino-libs/ESP32_Display_Panel/blob/master/examples/README.md#using-custom-development-boards) to configure it.`
The link didn't work.  I get:
`404 - page not found`

**Comment by Lzw655** [comment]
Hi @mrmonteith, thank you for pointing out this issue. I'll fix this issue right away.
