### ISSUE TITLE
DrawBitmap crashing if logging not enabled

### ISSUE THREAD

**Issue by NecroMancer05** [esp-arduino-libs/ESP32_Display_Panel#112]
Hello, @Lzw655 

I am using LVGL with this library with PlatformIO. I have enabled all logs with adding CORE_DEBUG_LEVEL=5 to build flags in platformio.ini file.
But after removing CORE_DEBUG_LEVEL line im getting crash on `panel->getLcd()->drawBitmap` call. Also its crashing below log level < 3 like CORE_DEBUG_LEVEL=2, CORE_DEBUG_LEVEL=1.

Heres my platformio.ini file contents.

![platformio.ini](https://github.com/user-attachments/assets/a901df39-d47e-4a85-8031-eb62f1788bbb)

Is it related to me or someting wrong with the library?

Thanks.

**Comment by Lzw655** [comment]
Hi @NecroMancer05, could you please send the serial output log from when the crash occurred?

**Comment by NecroMancer05** [comment]
Hi @Lzw655,

Now i found the issue. 
i have a log call like this `log_i("Lcd init %d", panel->init());` and after disabling logs panel::init function not calling so thats why im getting crash 😂

Thanks.
