### ISSUE TITLE
What does the Panel test look like on the screen?

### ISSUE THREAD

**Issue by CoTECH1987** [esp-arduino-libs/ESP32_Display_Panel#114]
Hi. I have compiled a test sketch of Test Panel.ino
from examples of the latest version of the ESP32_Display_Panel library.
But it seems to me that the example is not displayed correctly.
Maybe someone has a picture of what the sample should actually look like after compilation?
![Screenshot_20241024_184836_Gallery](https://github.com/user-attachments/assets/cd826917-c369-47ec-a5bc-6a45456cf8ab)
I'm a little unsure about the black rectangle and the thin white stripe on top

**Comment by Lzw655** [comment]
Hi @CoTECH1987, Could you please share your test sketch of Test Panel.ino?

**Comment by CoTECH1987** [comment]
[TEST_PANEL_TYPE_RGB.zip](https://github.com/user-attachments/files/17520591/TEST_PANEL_TYPE_RGB.zip)

**Comment by CoTECH1987** [comment]
I have set up my sketch for https://www.waveshare.com/wiki/ESP32-S3-Touch-LCD-5
this is a parallel RGB interface.

**Comment by CoTECH1987** [comment]
![photo_2024-10-25_14-51-55](https://github.com/user-attachments/assets/c15d5253-6135-475b-9a88-d1c84ecc906e)

I think I've figured out the black square.
I changed the bus settings for the 1024x600 LCD as follows:

`#elif ESP_PANEL_LCD_BUS_TYPE == ESP_PANEL_BUS_TYPE_RGB

    #define ESP_PANEL_LCD_RGB_CLK_HZ            (20 * 1000 * 1000)
    #define ESP_PANEL_LCD_RGB_HPW               (88)
    #define ESP_PANEL_LCD_RGB_HBP               (188)
    #define ESP_PANEL_LCD_RGB_HFP               (44)
    #define ESP_PANEL_LCD_RGB_VPW               (6)
    #define ESP_PANEL_LCD_RGB_VBP               (16)
    #define ESP_PANEL_LCD_RGB_VFP               (3)
    #define ESP_PANEL_LCD_RGB_PCLK_ACTIVE_NEG   (1) `

But I'm still worried about the white stripe on the top and bottom now.
And I noticed that every time I click on the touchpad, my graphics on the display slides by several pixels, this can be seen if you zoom in on the picture.
Any help?

**Comment by CoTECH1987** [comment]
![photo_2024-10-25_15-02-52](https://github.com/user-attachments/assets/017c9a71-fcb9-408d-aea1-b54997b4bcba)

If you keep the touchpad pressed, this session will happen all the time!

**Comment by CoTECH1987** [comment]
It's been decided. The offset was due to the internal features of the esp-sdk. Installing the patched version solved the problem! thank you!

**Comment by CoTECH1987** [comment]
!!!
