### ISSUE TITLE
missing file

### ISSUE THREAD

**Issue by minou65** [esp-arduino-libs/ESP32_Display_Panel#139]
Hi
When I use this lib and rey do compile I recive this error

RGB.h:14: In file included from
esp_panel_library.h:22: from
ESP32-Wanduhr.ino:7: from

esp_lcd_panel_io_additions.h: 12:10: fatal error: base/esp_io_expander.h: No such file or directory
12 | #include "base/esp_io_expander.h"
| ^~~~~~~~~~~~~~~~~~~~~~~~

I dont find the file, also not on github in this lib. Is this file needed or can I comment it out?

**Comment by UmmonPwr** [comment]
Hi, I also run into this problem.

The ESP_IO_Expander library from version 1.0.0 has changed the filenames. Now the include is called "ESP_IOExpander_Library.h".
As short term solution go back to version 0.1.0 and wait for the devs to update this library :)

**Comment by Lzw655** [comment]
Hi @minou65, @UmmonPwr is right. Please use the ESP_IO_Expander library v0.1.0, which meets the requirements of this library currently.

**Comment by minou65** [comment]
Hi @UmmonPwr , @Lzw655 
Yes that resolved the Problem. Thanks!

**Comment by minou65** [comment]
resolved
