### ISSUE TITLE
typo

### ISSUE THREAD

**Issue by Franck78** [esp-arduino-libs/ESP32_Display_Panel#17]
https://github.com/esp-arduino-libs/ESP32_Display_Panel/blob/bd59067b8b1318f54b8a1b558b3d58ed5dcc377f/src/ESP_Panel_Conf_Internal.h#L82

The comment should be about "ESP_Panel_Board_Custom.h" , not "Board Supported"

**Comment by Lzw655** [comment]
Hi @Franck78, thank you for pointing out this issue. I will fix it in the next version.
