### ISSUE TITLE
SquareLine Porting Example --> error: 'ESP_Panel' does not name a type

### ISSUE THREAD

**Issue by lboue** [esp-arduino-libs/ESP32_Display_Panel#24]
Hello,

I try to build this demo file [Porting.ino](https://github.com/esp-arduino-libs/ESP32_Display_Panel/blob/master/examples/SquareLine/v8/Porting/Porting.ino) but I get a build error in the Arduino IDE: `error: 'ESP_Panel' does not name a type`.

Can you help me correct this error?

### Step to reproduce
* Install [arduino-esp32 3.0.0-rc1](https://github.com/espressif/arduino-esp32/releases/tag/3.0.0-rc1)
* Copy this Githup repo
* Edit `ESP_Panel_Board_Custom.h`
* Build demo file [Porting.ino](https://github.com/esp-arduino-libs/ESP32_Display_Panel/blob/master/examples/SquareLine/v8/Porting/Porting.ino)

### Log file

[SquareLine_v8_Porting_build_error.log](https://github.com/esp-arduino-libs/ESP32_Display_Panel/files/15287150/SquareLine_v8_Porting_build_error.log)

**Comment by Lzw655** [comment]
Hi @lboue, did you set the macro `ESP_PANEL_USE_CUSTOM_BOARD` to `1` in the file `ESP_Panel_Board_Custom.h`?

**Comment by lboue** [comment]
> Hi @lboue, did you set the macro `ESP_PANEL_USE_CUSTOM_BOARD` to `1` in the file `ESP_Panel_Board_Custom.h`?

Thanks. It build now.
