### ISSUE TITLE
ESP-IDF Support

### ISSUE THREAD

**Issue by VoytkoValera** [esp-arduino-libs/ESP32_Display_Panel#39]
I want to build my project using esp idf plugin for vscode, for this I wrote idf_component.yml where I included the commits of the latest tags of the necessary dependencies, however, on the side I get
Failed to resolve component 'esp-io-expander'.

idf_component.yml
`dependencies:
  espressif/arduino-esp32:
    git: https://github.com/espressif/arduino-esp32.git
    version: b3ad98cbf6162b07719c6f9e587cdef0ed00ea2b
  lzw655/esp32_io_expander: 
    git: https://github.com/esp-arduino-libs/ESP32_IO_Expander.git
    version: e5378da3345a9ddbecb710d868a0ee1b382e576f
  lzw655/esp32_display_panel: 
    git: https://github.com/esp-arduino-libs/ESP32_Display_Panel.git
    version: 4a7d5a0bdd455cf6456987b1c560e43d7788d687
  lvgl/lvgl: "=8.3.11"
  idf:
    version: "=5.1.4"`

error:
`-- Found Git: C:/Users/Valera/.espressif/tools/idf-git/2.39.2/cmd/git.exe (found version "2.39.2.windows.1") 
-- Component directory C:/Users/Valera/Documents/Lesha/test/components/arduino-esp32 does not contain a CMakeLists.txt file. No component will be added
-- The C compiler identification is GNU 12.2.0
-- The CXX compiler identification is GNU 12.2.0
-- The ASM compiler identification is GNU
-- Found assembler: C:/Users/Valera/.espressif/tools/xtensa-esp32s3-elf/esp-12.2.0_20230208/xtensa-esp32s3-elf/bin/xtensa-esp32s3-elf-gcc.exe
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: C:/Users/Valera/.espressif/tools/xtensa-esp32s3-elf/esp-12.2.0_20230208/xtensa-esp32s3-elf/bin/xtensa-esp32s3-elf-gcc.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: C:/Users/Valera/.espressif/tools/xtensa-esp32s3-elf/esp-12.2.0_20230208/xtensa-esp32s3-elf/bin/xtensa-esp32s3-elf-g++.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Building ESP-IDF components for target esp32s3
Processing 25 dependencies:
[1/25] chmorgan/esp-libhelix-mp3 (1.0.3)
[2/25] espressif/arduino-esp32 (b3ad98cbf6162b07719c6f9e587cdef0ed00ea2b)
[3/25] espressif/cbor (0.6.0~1)
[4/25] espressif/esp-dsp (1.4.12)
[5/25] espressif/esp-sr (1.7.1)
[6/25] espressif/esp-zboss-lib (1.3.2)
[7/25] espressif/esp-zigbee-lib (1.3.2)
[8/25] espressif/esp_diag_data_store (1.0.1)
[9/25] espressif/esp_diagnostics (1.1.0)
[10/25] espressif/esp_insights (1.1.0)
[11/25] espressif/esp_modem (1.1.0)
[12/25] espressif/esp_rainmaker (1.1.0)
[13/25] espressif/esp_schedule (1.1.1)
[14/25] espressif/esp_secure_cert_mgr (2.4.1)
[15/25] espressif/jsmn (1.1.0)
[16/25] espressif/json_generator (1.1.2)
[17/25] espressif/json_parser (1.0.3)
[18/25] espressif/mdns (1.3.1)
[19/25] espressif/qrcode (0.1.0~2)
[20/25] espressif/rmaker_common (1.4.5)
[21/25] idf (5.1.4)
[22/25] joltwallet/littlefs (1.14.4)
[23/25] lvgl/lvgl (8.3.11)
[24/25] lzw655/esp32_display_panel (4a7d5a0bdd455cf6456987b1c560e43d7788d687)
[25/25] lzw655/esp32_io_expander (e5378da3345a9ddbecb710d868a0ee1b382e576f)
CMake Error at C:/Users/Valera/esp/v5.1.4/esp-idf/tools/cmake/build.cmake:266 (message):
  Failed to resolve component 'esp-io-expander'.
Call Stack (most recent call first):
  C:/Users/Valera/esp/v5.1.4/esp-idf/tools/cmake/build.cmake:302 (__build_resolve_and_add_req)
  C:/Users/Valera/esp/v5.1.4/esp-idf/tools/cmake/build.cmake:309 (__build_expand_requirements)
  C:/Users/Valera/esp/v5.1.4/esp-idf/tools/cmake/build.cmake:595 (__build_expand_requirements)
  C:/Users/Valera/esp/v5.1.4/esp-idf/tools/cmake/project.cmake:604 (idf_build_process)
  CMakeLists.txt:6 (project)`

**Comment by Lzw655** [comment]
Hi @VoytkoValera,

Thank you for reporting this issue. With the update from version 0.0.x to version 0.1.x, the library undergoes certain changes. One change involves the removal of the `Kconfig` file, while another issue arises with an incorrect `CMakeLists.txt` file which leads to build errors.

So, currently, the library no longer supports direct building with ESP-IDF. I will do my best to fix these issues as soon as possible.
