### ISSUE TITLE
Squareline Simple Wi-Fi Clock Example: How to set hardcoded Wi-Fi credentials?

### ISSUE THREAD

**Issue by lboue** [esp-arduino-libs/ESP32_Display_Panel#49]
# Squareline Simple Wi-Fi Clock Example

I haven't worked out how to set Wi-Fi credentials for [Squareline Simple Wi-Fi Clock Example](https://github.com/esp-arduino-libs/ESP32_Display_Panel/blob/master/examples/SquareLine/v8/WiFiClock) encoded directly in the code. Could you  tell me how to do that?

Regards

**Comment by Horion0415** [comment]
Hello, considering the convenience of connecting to Wi-Fi, this project is designed to configure the network through the UI in the settings. Therefore, configuring the network in the code is not supported at the moment. This feature might be supported in future updates. Alternatively, you can modify it according to your needs. You can refer to the Wi-Fi examples for the Wi-Fi configuration code.
