### ISSUE TITLE
release v0.1.4 - 2024-06-17 version

### ISSUE THREAD

**Issue by lboue** [esp-arduino-libs/ESP32_Display_Panel#55]
Hello,

Could you release v0.1.4 - 2024-06-17 version bumped here: https://github.com/esp-arduino-libs/ESP32_Display_Panel/commit/30f83601b0ac64bdf21ff4ee17189d887c2af1f0?

Regards

**Comment by Lzw655** [comment]
Hi @lboue,

Sure, we can release any time. But I usually prefer to accumulate enough changes before releasing. May I ask the reason for this?

**Comment by lboue** [comment]
It's actually better to wait for patches. Perfect timing for #56.

**Comment by Lzw655** [comment]
Ok, I get it.
