### ISSUE TITLE
EXAMPLE_TOUCH_ADDRESS missing as variable.

### ISSUE THREAD

**Issue by lboue** [esp-arduino-libs/ESP32_Display_Panel#83]
`EXAMPLE_TOUCH_ADDRESS` missing as variable in I2C.ino

https://github.com/esp-arduino-libs/ESP32_Display_Panel/blob/289d3575fee397d5ef80e10576b92497299db4a2/examples/Touch/I2C/I2C.ino#L103-L104

**Comment by Lzw655** [comment]
Hi @lboue, thank you very much for your contributions.
