### ISSUE TITLE
WiFiClock example: Poor graphics quality

### ISSUE THREAD

**Issue by lboue** [esp-arduino-libs/ESP32_Display_Panel#87]
## Issue

[WiFiClock example](https://github.com/esp-arduino-libs/ESP32_Display_Panel/tree/master/examples/SquareLine/v8/WiFiClock): Poor graphics quality with [M5STACK_M5CORES3](https://docs.m5stack.com/en/core/CoreS3) board.

## Steps to 

1. Build [WiFiClock example](https://github.com/esp-arduino-libs/ESP32_Display_Panel/tree/master/examples/SquareLine/v8/WiFiClock) for [M5STACK_M5CORES3](https://docs.m5stack.com/en/core/CoreS3)

![0](https://github.com/user-attachments/assets/1ab5a06e-3b2e-4a15-8b8e-e9066b0a657c)

**Comment by Lzw655** [comment]
Hi @lboue, did you try to set `LV_COLOR_16_SWAP` to `1` ?

**Comment by lboue** [comment]
> Hi @lboue, did you try to set `LV_COLOR_16_SWAP` to `1` ?

@Lzw655 
I've just tested it by setting this variable as indicated in the `lv_conf.h` file.
I haven't noticed any significant difference.

**Comment by Lzw655** [comment]
I tried modifying `LV_COLOR_16_SWAP`, and the UI is displaying correctly. Could you please confirm if the correct file was modified?

![6da81ab9c6d5f4cdbee162b2479b6340_compress](https://github.com/user-attachments/assets/d02adeca-ce89-498a-9109-3d63332d318a)

**Comment by lboue** [comment]
> I tried modifying `LV_COLOR_16_SWAP`, and the UI is displaying correctly. Could you please confirm if the correct file was modified?

Yes, It doesn't work in my case. 
Can I have your binary file for testing? Here's mine:
[WiFiClock.ino.merged.bin.txt](https://github.com/user-attachments/files/16408006/WiFiClock.ino.merged.bin.txt)

**lv_conf.h config file**

https://github.com/lboue/ESP32_Display_Panel/blob/CoreS3_testing/examples/SquareLine/v8/WiFiClock/libraries/lv_conf.h

**Comment by Lzw655** [comment]
Here are mine:

[lv_conf.h.txt](https://github.com/user-attachments/files/16409821/lv_conf.h.txt)
[WiFiClock.ino.merged.bin.txt](https://github.com/user-attachments/files/16409822/WiFiClock.ino.merged.bin.txt)

**Comment by lboue** [comment]
Setting this line to 1 fixed my issue.

`#if 0 /*Set it to "1" to enable content*/
`
https://github.com/lboue/ESP32_Display_Panel/blob/17d60252b86d6ed134239054f1699165c1b9a941/examples/SquareLine/v8/WiFiClock/libraries/lv_conf.h#L15

Do you know why?
